version: "3.1"
services:
  postgres:
    image: postgres:9.5-alpine
    container_name: ${APP_NAME}-db
    volumes:
      - "./docker-files/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=webmaster
      - POSTGRES_PASSWORD=webmaster
      - POSTGRES_DB=slim_project
    ports:
      - "9876:5432"
    networks:
      testing_net:
        ipv4_address: 91.28.1.2

  webserver:
    image: nginx:alpine
    container_name: ${APP_NAME}-webserver
    working_dir: /
    volumes:
      - "./:/app"
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "8888:8888"
    networks:
      testing_net:
        ipv4_address: 91.28.1.3

  php-fpm:
    build: docker/php-fpm
    container_name: ${APP_NAME}-php-fpm
    working_dir: /
    volumes:
      - "./:/app"
      - "./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini"
    networks:
      testing_net:
        ipv4_address: 91.28.1.4

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 91.28.0.0/16
