main:
  method: 'get'
  path: ~
  controller: App\Controller\HomeController
  action: index

movie_show:
  method: 'get'
  path: movies/{id}
  controller: App\Controller\MovieController
  action: show
