main:
  method: 'get'
  path: ~
  controller: App\Controller\HomeController
  action: index

movie_show:
  method: 'get'
  path: movies/{id}
  controller: App\Controller\MovieController
  action: show

movie_like:
  method: 'get'
  path: like-movie/{id}
  controller: App\Controller\MovieController
  action: like

movie_dislike:
  method: 'get'
  path: dislike-movie/{id}
  controller: App\Controller\MovieController
  action: dislike

user_register:
  method: 'get'
  path: signup
  controller: App\Controller\UserController
  action: showRegisterForm

user_login_form:
  method: 'get'
  path: signin
  controller: App\Controller\UserController
  action: showLoginForm

user_login:
  method: 'post'
  path: signin
  controller: App\Controller\UserController
  action: login

user_store:
  method: 'post'
  path: signup
  controller: App\Controller\UserController
  action: store

user_logout:
  method: 'get'
  path: logout
  controller: App\Controller\UserController
  action: logout
